# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      # Runs a single command using the runners shell
      - name: Build and Remove src
        run: | 
          npm i
          npm run build
          rm -r ./src ./node_modules ./.github .gitignore 
          echo "Dir like:"
          echo "=================="
          pwd
          echo "=================="
          ls -al
          echo "=================="
          git checkout -b build
          gir add .
          # git commit -m "$(date +"%T") - Build"
      
      - name: Workspace Commit
        # You may pin to the exact commit or the version.
        # uses: gha-utilities/workspace-commit@c6bd2e34ef76c161faa65601136da13ac46d784f
        uses: gha-utilities/workspace-commit@v0.0.3
        with:
          message: "Build"
          
      - name: GitHub Push
        # You may pin to the exact commit or the version.
        # uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        uses: ad-m/github-push-action@v0.6.0
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      
      - name: ssh pipelines
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.LOGIN }}
          pass: ${{ secrets.PASSWORD }}
          port: 22
          connect_timeout: 30s
          script: |
            cd ${{ secrets.TARGET }}
            git pull origin build
            rm restart.txt
            touch restart.txt
