name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Installing node_modules
        run: npm ci

      - name: Build and Remove src
        run: |
          echo "Building..."
          echo "=================="
          npm run build
          echo "=================="
          echo "Building done!"
          rm -r ./src ./node_modules ./.github .gitignore
          echo "Dir like:"
          echo "=================="
          pwd
          echo "=================="
          ls -al
          echo "=================="
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "$(date +"%T") - Build" -a

      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: 'build'
